n_1  = int(input("first number : "))
n_2 = int(input("second number : "))
print(n_1," + ",n_2," = ",n_1+n_2)
print(n_1," - ",n_2," = ",n_1-n_2)
print(n_1," * ",n_2," = ",n_1*n_2)
print(n_1," / ",n_2," = ",n_1/n_2)